name: Fetch Kick Streams VODs v2

on:
  # schedule:
  #    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  fetch-streams:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install curl_cffi

      - name: Fetch Kick streams
        run: python scripts/fetch_streams.py

      - name: Commit metadata updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data
          git commit -m "Update Kick VOD metadata" || echo "No changes"
          git push
