name: Test Kick Chat Downloader

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Clone repo
        run: |
          git clone https://github.com/lay295/TwitchDownloader.git
          cd TwitchDownloader
          git checkout kick-support

      - name: Build CLI only
        run: |
          cd TwitchDownloader/TwitchDownloaderCLI
          dotnet build

      - name: Show CLI commands
        run: |
          cd TwitchDownloader/TwitchDownloaderCLI/bin/Debug/net8.0
          ./TwitchDownloaderCLI --help
